version: '3.2'
networks:
  monitoring:
    driver: bridge
services:
  #=======Prometheus Service===================================
  prometheus_m1:
    image: prom/prometheus:${PROMETHEUS_TAG}
    container_name: prometheus_m1
    ports:
    - 9090:9090
    networks:
      - monitoring
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus/master/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    
  prometheus_s1:
    image: prom/prometheus:${PROMETHEUS_TAG}
    container_name: prometheus_s1
    #ports:
    #- 9091:9090
    networks:
      - monitoring
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.listen-address=0.0.0.0:9090
    volumes:
    - ./prometheus/slave/prometheus1.yml:/etc/prometheus/prometheus.yml:ro
    
  prometheus_s2:
    image: prom/prometheus:${PROMETHEUS_TAG}
    container_name: prometheus_s2
    #ports:
    #- 9092:9090
    networks:
      - monitoring
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.listen-address=0.0.0.0:9090
    volumes:
    - ./prometheus/slave/prometheus2.yml:/etc/prometheus/prometheus.yml:ro
  
  #=======Containers whose metrics will be collected=======
  node_exporter1:
    image: prom/node-exporter:${NODE_EXPORTER_TAG}
    container_name: node_exporter1
    networks:
      - monitoring
    
  node_exporter2:
    image: prom/node-exporter:${NODE_EXPORTER_TAG}
    container_name: node_exporter2
    networks:
      - monitoring
    
  #=======Grafana Service===================================
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root:root
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${grafana_user}
      - GF_SECURITY_ADMIN_PASSWORD=${grafana_pass}
    
