global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
    region: "slave1"
rule_files:
scrape_configs:
  - job_name: node_exporter
    static_configs:
      - targets: ['node_exporter1:9100']
