{
 "title": "CNF_Machine_System_Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Ortam", "label": "Ortam", "query": { "query": "label_values(group)" } },
   {
    "name": "Hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values({group=~\"(?i:($Ortam))\"},mac_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Load (1m, 5m, 15m): $Hostname",
   "type": "graph",
   "description": "1, 5, 15 dakikalık işlemci yükü.\n\nÖrnek: load average: 1.00, 0.40, 3.35\n\nTek çekirdek için:\n\nSon 1 dakikada %100 kullanım.\n\nSon 5 dakikada %40 kullanım.\n\nSon 15 dakikada %235 aşırı yüklenme.\n\nDual core için:\n\nSon 1 dakikada ortalama olarak 1 CPU kullanılmış, 1 CPU boşta.\n\nSon 5 dakikada CPU'lar %160 boşta.\n\nSon 15 dakikada %135 aşırı yüklenme.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "repeat": "Hostname",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
     "legendFormat": "{{mac_name}} {{instance}} - 1m"
    },
    {
     "expr": "node_load5{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
     "legendFormat": "{{mac_name}} {{instance}} - 5m"
    },
    {
     "expr": "node_load15{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
     "legendFormat": "{{mac_name}} {{instance}} - 15m"
    }
   ]
  },
  {
   "title": "Process schedule stats Running / Waiting: $Hostname",
   "type": "graph",
   "description": "node_schedstat_running_seconds_total: CPU'nın bir işlemi çalıştırmak için harcadığı süre.\n\nnode_schedstat_waiting_seconds_total: Bir CPU'yu beklerken işlenerek harcanan süre.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "repeat": "Hostname",
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_schedstat_running_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval] ) ) by(instance)",
     "legendFormat": "{{instance}} CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "sum(rate(node_schedstat_waiting_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])) by(instance)",
     "legendFormat": "{{instance}} CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "System Uptime: $Hostname",
   "type": "bargauge",
   "description": "Sistemin çalışma süresi (Unixtime)",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "repeat": "Hostname",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"})",
     "legendFormat": "{{mac_name}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Processes Status: $Hostname",
   "type": "graph",
   "description": "procs_running: Şu anda CPU'larda çalışan işlemlerin sayısı.\n\nprocs_blocked: Şu anda engellenen, I/O tamamlanmasını bekleyen işlemlerin sayısı.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "repeat": "Hostname",
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
     "legendFormat": "{{instance}} Processes blocked waiting for I/O to complete"
    },
    {
     "expr": "node_procs_running{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
     "legendFormat": "{{instance}} Processes in runnable state"
    }
   ]
  },
  {
   "title": "Context Switches / Interrupts: $Hostname",
   "type": "timeseries",
   "description": "node_intr_total: Hizmet verilen toplam interrupt sayısı\n\nnode_context_switches_total: Context switch sayısı",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "repeat": "Hostname",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
     "legendFormat": "{{instance}} - Context switches"
    },
    {
     "expr": "rate(node_intr_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
     "legendFormat": "{{instance}} - Interrupts"
    }
   ]
  },
  {
   "title": "Hardware Temperature Monitor: $Hostname",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "repeat": "Hostname",
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_alarm_celsius{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical Alarm"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    },
    {
     "expr": "node_hwmon_temp_crit_hyst_celsius{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical Historical"
    },
    {
     "expr": "node_hwmon_temp_max_celsius{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Max"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory (GB): $Hostname",
     "type": "stat",
     "description": "Makinenin toplam hafıza bilgisi.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 53 },
     "repeat": "Hostname",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage (GB): $Hostname",
     "type": "timeseries",
     "description": "Memory kullanımı (GB olarak)\n\nUsage = MemTotal - MemFree - Buffers - Cached",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "repeat": "Hostname",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"} - node_memory_MemFree_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"} - node_memory_Buffers_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"} - node_memory_Cached_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"})",
       "legendFormat": "{{mac_name}} {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage (%): $Hostname",
     "type": "gauge",
     "description": "Memory kullanımı (% olarak)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
     "repeat": "Hostname",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval]) + avg_over_time(node_memory_Cached_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval]) + avg_over_time(node_memory_Buffers_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])) / avg_over_time(node_memory_MemTotal_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])))",
       "legendFormat": "{{mac_name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Memory HugePages Size: $Hostname",
     "type": "graph",
     "description": "node_memory_HugePages_Total: Toplam huge pages boyutu.\n\nnode_memory_Hugepagesize_bytes: Huge page boyutu",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_HugePages_Total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
       "legendFormat": "{{instance}} HugePages - Total size of the pool of huge pages"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
       "legendFormat": "{{instance}} Hugepagesize - Huge Page size"
      }
     ]
    },
    {
     "title": "Memory HugePages Counter: $Hostname",
     "type": "graph",
     "description": "HugePages_Free: Havuzdaki henüz tahsis edilmemiş page sayısı.\n\nHugePages_Rsvd: 'Reserved'. Havuzdan tahsis taahhüdü verilmiş ancak henüz tahsis yapılmamış huge page sayısı. Ayrılmış huge pages bir uygulamanın fault zamanında huge pages havuzundan bir huge page tahsis edileceğini garanti eder.\n\nHugePages_Surp: 'Artan'. Havuzdaki /proc/sys/vm/nr_hugepages içindeki değerin üzerindeki huge pages miktarıdır. Maximum surplus huge page miktarı ise /proc/sys/vm/nr_overcommit_hugepages tarafından kontrol edilir.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "short", "label": "pages" }
     ],
     "targets": [
      {
       "expr": "node_memory_HugePages_Free{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
       "legendFormat": "{{instance}} HugePages_Free - Huge pages in the pool that are not yet allocated"
      },
      {
       "expr": "node_memory_HugePages_Rsvd{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
       "legendFormat": "{{instance}} HugePages_Rsvd - Huge pages for which a commitment to allocate from the pool has been made, but no allocation has yet been made"
      },
      {
       "expr": "node_memory_HugePages_Surp{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
       "legendFormat": "{{instance}} HugePages_Surp - Huge pages in the pool above the value in /proc/sys/vm/nr_hugepages"
      }
     ]
    },
    {
     "title": "Memory Pages Swap In / Out: $Hostname",
     "type": "graph",
     "description": "node_vmstat_pswpin & node_vmstat_pswpout\n\npswpout: Sistemin saniyede diske swap ettiği page sayısı.\n\npswpin: Sistemin saniyede diskten swap ettiği page sayısı.\n\n/proc/vmstat information",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "short", "label": "pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pswpin{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} Pswpin - Pages swapped in"
      },
      {
       "expr": "rate(node_vmstat_pswpout{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} Pswpout - Pages swapped out"
      }
     ]
    },
    {
     "title": "Memory Pages In / Out: $Hostname",
     "type": "graph",
     "description": "node_vmstat_pgpgin & node_vmstat_pgpgout:\n\nPage-out: Sayfaların diske yazılması\n\nPage-in: Sayfaların fiziksel belleğe yazılması\n\n/proc/vmstat information",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "short", "label": "pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgpgin{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} Pagesin - Page in operations"
      },
      {
       "expr": "rate(node_vmstat_pgpgout{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} Pagesout - Page out operations"
      }
     ]
    },
    {
     "title": "Memory Page Faults: $Hostname",
     "type": "graph",
     "description": "node_vmstat_pgfault: Sistemin saniyede yaptığı page fault sayısı\n\nnode_vmstat_pgmajfault: Sistemin diskten bir memory page yüklemesi için gereken saniyedeki major fault sayısı\n\nnode_vmstat_pgfault - node_vmstat_pgmajfault: Minor fault sayısı\n\nSistem yavaş çalıştığında bakılabilir. Page fault sayısı çok hızlı artar, bu da kullanımda olan çok fazla bellek nedeniyle bozulma olduğunu ve kullanılabilir bir bellek için çok az kaldığını gösterebilir.\n\n/proc/vmstat information",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 105 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "short", "label": "faults" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgfault{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} Pgfault - Page major and minor fault operations"
      },
      {
       "expr": "rate(node_vmstat_pgmajfault{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} Pgmajfault - Major page fault operations"
      },
      {
       "expr": "rate(node_vmstat_pgfault{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])  - rate(node_vmstat_pgmajfault{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} Pgminfault - Minor page fault operations"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores: $Hostname",
     "type": "stat",
     "description": "Toplam CPU çekirdek sayısı",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "repeat": "Hostname",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}) without (mode)) without (cpu)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage (Avg %): $Hostname",
     "type": "timeseries",
     "description": "Makinenin ortalama CPU kullanımı.\n\nHesaplamanın %(100 - idle) şeklinde olduğuna (User + System) dikkat ediniz.\n\nUser, System, iowait, Total için diğer grafiğe bakınız.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "repeat": "Hostname",
     "targets": [
      {
       "expr": "100 - (avg by(instance,mac_name) (irate(node_cpu_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mode=\"idle\"}[5m])) * 100 )",
       "legendFormat": "{{mac_name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "% CPU (modes): $Hostname",
     "type": "graph",
     "description": "CPU kullanımı (system + user + iowait + softirq + steal = total)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mode=\"system\"}[$__interval])) by (instance,mac_name) * 100",
       "legendFormat": "{{mac_name}}  {{instance}} - System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mode=\"user\"}[$__interval])) by (instance,mac_name) * 100",
       "legendFormat": "{{mac_name}}  {{instance}} - User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mode=\"iowait\"}[$__interval])) by (instance,mac_name) * 100",
       "legendFormat": "{{mac_name}}  {{instance}} - Iowait"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mode=\"softirq\"}[$__interval])) by (instance,mac_name) * 100",
       "legendFormat": "{{mac_name}}  {{instance}} - Softirq"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mode=\"steal\"}[$__interval])) by (instance,mac_name) * 100",
       "legendFormat": "{{mac_name}}  {{instance}} - Steal"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mode=\"nice\"}[$__interval])) by (instance,mac_name) * 100",
       "legendFormat": "{{mac_name}}  {{instance}} - Nice"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mode=\"idle\"}[$__interval])) by (instance,mac_name)) * 100",
       "legendFormat": "{{mac_name}}  {{instance}} - Total"
      }
     ]
    },
    {
     "title": "CPUs Usage: $Hostname",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
     "repeat": "Hostname",
     "targets": [
      {
       "expr": "100 - ((irate(node_cpu_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mode=\"idle\"}[5m])) * 100 )",
       "legendFormat": "CPU: {{cpu}} - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space (%): $Hostname",
     "type": "gauge",
     "description": "% disk doluluğu",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "repeat": "Hostname",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "{{mac_name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Space (Time): $Hostname",
     "type": "timeseries",
     "description": "Zamana göre disk doluluğu. Diskin hangi anda dolmaya başladığı görülerek ilgili uygulamadan şüphelenilebilir.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "repeat": "Hostname",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mountpoint=\"/\",fstype!=\"rootfs\"} - node_filesystem_avail_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",mountpoint=\"/\",fstype!=\"rootfs\"}",
       "legendFormat": "{{mac_name}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk IOps: $Hostname",
     "type": "graph",
     "description": "node_disk_reads_completed_total: Başarıyla tamamlanan toplam okuma sayısı\n\nnode_disk_writes_completed_total: Başarıyla tamamlanan toplam yazma sayısı",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} {{device}} - Reads completed"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} {{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write: $Hostname",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "Bps", "label": "bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} {{device}} - Successfully read bytes"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} {{device}} - Successfully written bytes"
      }
     ]
    },
    {
     "title": "I/O Utilization: $Hostname",
     "type": "graph",
     "description": "node_disk_io_time_seconds_total: I/O yapmak için harcanan toplam saniye",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "percentunit", "label": "%util" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"} [$__interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic (Receive & Transmit): $Hostname",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 56 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[$__interval])*8",
       "legendFormat": "{{mac_name}} {{instance}}_{{device}}_receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[$__interval])*8",
       "legendFormat": "{{mac_name}} {{instance}}_{{device}}_transmit"
      }
     ]
    },
    {
     "title": "Network Traffic by Packets: $Hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} - {{device}} - Receive"
      },
      {
       "expr": "rate(node_network_transmit_packets_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} - {{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Errors: $Hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_errs_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} - {{device}} - Receive errors"
      },
      {
       "expr": "rate(node_network_transmit_errs_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} {{device}} - Transmit errors"
      }
     ]
    },
    {
     "title": "Network Traffic Drop: $Hostname",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 91 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "pps", "label": "packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_drop_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} - {{device}} - Receive drop"
      },
      {
       "expr": "rate(node_network_transmit_drop_total{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}[$__interval])",
       "legendFormat": "{{instance}} - {{device}} - Transmit drop"
      }
     ]
    },
    {
     "title": "MTU: $Hostname",
     "type": "graph",
     "description": "maximum transfer unit",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 102 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_network_mtu_bytes{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
       "legendFormat": "{{instance}} - {{ device }} - Bytes"
      }
     ]
    },
    {
     "title": "Queue Length: $Hostname",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 115 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "none", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "node_network_transmit_queue_length{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
       "legendFormat": "{{instance}} - {{ device }} -   Interface transmit queue length"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter Scrape Time: $Hostname",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
     "repeat": "Hostname",
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{group=~\"(?i:($Ortam))\",mac_name=~\"$Hostname\"}",
       "legendFormat": "{{instance}} - {{collector}} - Scrape duration"
      }
     ]
    }
   ]
  }
 ]
}